#!/usr/bin/env python3
"""Generate paired RMAPPO baseline / GSD-Sparse SMAC training scripts.

Only per-map *episode* configuration lives here. Observation dimensions are
NOT declared: the SMAC HeteroGraph derives n_allies, n_enemies, ally_feat_dim,
enemy_feat_dim, agent_state_dim and ctx_dim from the environment's structured
observation space at runtime. Run detect_smac_dimensions.py if you want to see
what those values are for a given map.

Each map yields two scripts that are identical in every RMAPPO hyperparameter.
The only difference is the presence of --use_hetero_graph (plus the GSD-Sparse
sparsity parameters), so the comparison isolates the method.
"""

import os

# map_name -> (episode_length, num_env_steps)
MAP_EPISODES = {
    "3m": (60, 10000000),
    "8m": (120, 10000000),
    "25m": (150, 10000000),

    "2m_vs_1z": (150, 10000000),
    "3s_vs_3z": (150, 10000000),
    "3s_vs_4z": (200, 10000000),
    "3s_vs_5z": (250, 10000000),
    "5m_vs_6m": (70, 10000000),
    "8m_vs_9m": (120, 10000000),
    "10m_vs_11m": (150, 10000000),
    "27m_vs_30m": (180, 10000000),

    "2s_vs_1sc": (300, 10000000),
    "1c3s5z": (150, 10000000),
    "3s5z": (150, 10000000),
    "3s5z_vs_3s6z": (170, 10000000),
    "6h_vs_8z": (150, 10000000),

    "corridor": (400, 10000000),
    "MMM": (150, 10000000),
    "MMM2": (180, 10000000),
    "2c_vs_64zg": (400, 10000000),

    "bane_vs_bane": (200, 10000000),
    "baneling": (200, 10000000),
}

# Shared RMAPPO settings. Both arms of a pair use these verbatim.
COMMON_ARGS = """--env_name ${{env}} --algorithm_name ${{algo}} --experiment_name ${{exp}} \\
    --map_name ${{map}} --seed ${{seed}} \\
    --n_training_threads 1 --n_rollout_threads 8 \\
    --num_mini_batch 1 --episode_length {episode_length} \\
    --num_env_steps {num_env_steps} --ppo_epoch 15 --clip_param 0.05 \\
    --lr 5e-4 --critic_lr 5e-4 --entropy_coef 0.01 --gain 0.01 \\
    --hidden_size 64 --use_value_active_masks --use_eval --eval_episodes 32"""

SCRIPT_TEMPLATE = """#!/bin/sh
# {arm_label} for {map_name}.
# Generated by generate_hetero_scripts_v2.py -- do not hand-edit dimensions:
# SMAC graph dimensions are derived from the environment at runtime.
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TRAIN="$SCRIPT_DIR/../train/train_smac.py"

env="StarCraft2"
map="{map_name}"
algo="rmappo"
exp="{exp_name}"
seed_max=1

echo "env is ${{env}}, map is ${{map}}, algo is ${{algo}}, exp is ${{exp}}, max seed is ${{seed_max}}"
for seed in `seq ${{seed_max}}`;
do
    echo "seed is ${{seed}}:"
    CUDA_VISIBLE_DEVICES=0 python "$TRAIN" {common_args}{extra_args}
done
"""

GSD_SPARSE_ARGS = """ \\
    --use_hetero_graph --k_max 10 --top_k_filter 5"""


def render(map_name, gsd_sparse):
    episode_length, num_env_steps = MAP_EPISODES[map_name]
    common = COMMON_ARGS.format(episode_length=episode_length,
                                num_env_steps=num_env_steps)
    return SCRIPT_TEMPLATE.format(
        map_name=map_name,
        arm_label='GSD-Sparse (RMAPPO + HeteroGraph)' if gsd_sparse else 'RMAPPO baseline',
        exp_name='rmappo_gsd_sparse' if gsd_sparse else 'rmappo_baseline',
        common_args=common,
        extra_args=GSD_SPARSE_ARGS if gsd_sparse else '',
    )


def main():
    output_dir = os.path.join('onpolicy', 'scripts', 'train_smac_hetero_scripts')
    os.makedirs(output_dir, exist_ok=True)

    written = 0
    for map_name in sorted(MAP_EPISODES):
        for gsd_sparse in (False, True):
            suffix = 'gsd_sparse' if gsd_sparse else 'baseline'
            path = os.path.join(
                output_dir, 'train_smac_{}_rmappo_{}.sh'.format(map_name, suffix))
            with open(path, 'w') as handle:
                handle.write(render(map_name, gsd_sparse))
            os.chmod(path, 0o755)
            written += 1
        print('paired: {:<16} baseline + gsd_sparse'.format(map_name))

    print('\nWrote {} scripts to {}/'.format(written, output_dir))
    print('Each pair shares every RMAPPO hyperparameter; the only difference is')
    print('--use_hetero_graph (+ --k_max/--top_k_filter) on the GSD-Sparse arm.')


if __name__ == '__main__':
    main()
