#!/bin/sh
# RMAPPO baseline for 27m_vs_30m.
# Generated by generate_hetero_scripts_v2.py -- do not hand-edit dimensions:
# SMAC graph dimensions are derived from the environment at runtime.
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TRAIN="$SCRIPT_DIR/../train/train_smac.py"

env="StarCraft2"
map="27m_vs_30m"
algo="rmappo"
exp="rmappo_baseline"
seed_max=1

echo "env is ${env}, map is ${map}, algo is ${algo}, exp is ${exp}, max seed is ${seed_max}"
for seed in `seq ${seed_max}`;
do
    echo "seed is ${seed}:"
    CUDA_VISIBLE_DEVICES=0 python "$TRAIN" --env_name ${env} --algorithm_name ${algo} --experiment_name ${exp} \
    --map_name ${map} --seed ${seed} \
    --n_training_threads 1 --n_rollout_threads 8 \
    --num_mini_batch 1 --episode_length 180 \
    --num_env_steps 10000000 --ppo_epoch 15 --clip_param 0.05 \
    --lr 5e-4 --critic_lr 5e-4 --entropy_coef 0.01 --gain 0.01 \
    --hidden_size 64 --use_value_active_masks --use_eval --eval_episodes 32
done
